name: streaming_asr
description: Sherpa ONNX Voice Assistant
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- UTILITIES ---
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  path: ^1.9.0
  
  # --- AUDIO ---
  record: ^6.1.2
  audioplayers: ^6.5.1
  
  # --- AI CORE ---
  sherpa_onnx: ^1.12.20
  
  # --- ZIP EXTRACTION ---
  archive: ^4.0.0

  # Extras from official
  url_launcher: ^6.3.1
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Ensure these files exist in your 'assets' folder!
    - assets/stt-hi.tar.bz2
    - assets/tts-hi.tar.bz2