name: streaming_asr
description: Sherpa ONNX Voice Assistant
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utils
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  
  # Audio
  record: ^6.1.2        # Stable version (AudioEncoder.wav support)
  audioplayers: ^6.0.0
  
  # AI Core
  sherpa_onnx: ^1.12.20 # Latest official
  
  # Zip Extract Karne ke liye (Important)
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # 1. STT Models
    - assets/tiny-encoder.int8.onnx
    - assets/tiny-decoder.int8.onnx
    - assets/tokens.txt
    
    # 2. TTS Models
    - assets/hi_IN-pratham-medium.onnx
    - assets/hi_IN-pratham-medium.onnx.json
    
    # 3. TTS Data (Zip File Only)
    # Folder mat use karna, files missing ho jati hain.
    - assets/espeak-ng-data.tar.bz2